/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadefila;

import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Aluno
 */
public class Fila extends javax.swing.JFrame {

    private List<String> fila;
    private int contador = 0;

    //criou uma variável com atributo de classe
    public Fila() {
        initComponents();
        this.fila = new LinkedList();
        this.contador = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelChamada = new javax.swing.JLabel();
        labelProximo = new javax.swing.JLabel();
        cpNome = new javax.swing.JTextField();
        btnIncluirCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnChamarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        labelUltimasChamadas = new javax.swing.JLabel();
        labelPessoa1 = new javax.swing.JLabel();
        labelPessoa2 = new javax.swing.JLabel();
        labelPessoa3 = new javax.swing.JLabel();
        labelPessoasFila = new javax.swing.JLabel();
        labelFilaPessoas = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelChamada.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        labelChamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChamada.setText("(chamada)");

        labelProximo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelProximo.setText("próximo:");

        cpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpNomeActionPerformed(evt);
            }
        });

        btnIncluirCliente.setText("Incluir cliente");
        btnIncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirClienteActionPerformed(evt);
            }
        });

        btnChamarCliente.setText("Chamar cliente");
        btnChamarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarClienteActionPerformed(evt);
            }
        });

        labelUltimasChamadas.setText("Últimas chamadas:");

        labelPessoa1.setText("(Pessoa1)");

        labelPessoa2.setText("(Pessoa2)");

        labelPessoa3.setText("(Pessoa3)");

        labelPessoasFila.setText("Pessoas na fila:");

        labelFilaPessoas.setText("(Nomes)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelChamada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChamarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnIncluirCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUltimasChamadas, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(labelPessoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPessoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPessoa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelPessoasFila)
                            .addComponent(labelFilaPessoas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProximo)
                .addGap(18, 18, 18)
                .addComponent(labelChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUltimasChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelPessoa1)
                .addGap(18, 18, 18)
                .addComponent(labelPessoa2)
                .addGap(19, 19, 19)
                .addComponent(labelPessoa3)
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(labelPessoasFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFilaPessoas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirCliente))
                .addGap(18, 18, 18)
                .addComponent(btnChamarCliente)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpNomeActionPerformed

    private void btnIncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirClienteActionPerformed
        //Incluir o clinte na lista, trim junto com  getText
        String nome = cpNome.getText().trim();

        cpNome.setText("");
        this.fila.add(nome);
    }//GEN-LAST:event_btnIncluirClienteActionPerformed

    private void btnChamarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarClienteActionPerformed
        // chamou o cliente da fila e depois trou assim que foi chamado

        if (this.fila.size() > 0) {
            String nome = this.fila.get(0);

            this.fila.remove(0);
            labelChamada.setText(nome);

            contador++;
            if (contador == 1) {
                labelPessoa1.setText(nome);
            }
            if (contador == 2) {
                labelPessoa2.setText(nome);
            }
            if (contador == 3) {
                labelPessoa3.setText(nome);
                contador = 0;
            }
            java.awt.Toolkit.getDefaultToolkit().beep();
            String FilaPessoas = "";
            
            for (int i = 0; i < this.fila.size(); i++) {
                FilaPessoas = FilaPessoas + "," + this.fila.get(i);

            }
               labelFilaPessoas.setText(FilaPessoas);
        }


    }//GEN-LAST:event_btnChamarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamarCliente;
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JTextField cpNome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelChamada;
    private javax.swing.JLabel labelFilaPessoas;
    private javax.swing.JLabel labelPessoa1;
    private javax.swing.JLabel labelPessoa2;
    private javax.swing.JLabel labelPessoa3;
    private javax.swing.JLabel labelPessoasFila;
    private javax.swing.JLabel labelProximo;
    private javax.swing.JLabel labelUltimasChamadas;
    // End of variables declaration//GEN-END:variables
}
